name: CI

on:
  push:
    branches:
      - main

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest

    needs: CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: yarn
          token: ${{ secrets.EAS_EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Get config file
        env:
          GOOGLE_SERVICE_64: ${{ secrets.EAS_GOOGLE_PLAY_API }}
        run: |
          echo $GOOGLE_SERVICE_64 > google-service.json.b64
          base64 -d -i google-service.json.b64 > google-service.json

      - name: Build and submit app
        run: EXPO_APPLE_SPECIFIC_PASSWORD=${{ secrets.EAS_APPLE_SPECIFIC_PASSWORD }} eas build --platform all --profile production --non-interactive --auto-submit-with-profile=production --no-wait
